# 异常

## 1. 了解异常

当检测到一个错误时，解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的“异常”。

```py
open('test.txt', 'r')

# Traceback (most recent call last):
#   File "/Users/ryu/PycharmProjects/demo/demo.py", line 1, in <module>
#     open('test.txt', 'r')
# FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'
```

### 1.1. 体验异常

需求：尝试以 r 模式打开文件，如果文件不存在，则以 w 模式打开

```py
"""
try:
    可能发生错误的代码
except:
    如果出现异常, 执行的代码
else:
    没有异常执行的代码
finally:
    无论是否异常都要执行的代码
"""
try:
    f = open('test.txt', 'r')
except:
    f = open('test.txt', 'w')
```

## 2. 捕获异常

### 2.1. 捕获指定异常类型

```py
"""
try:
    可能发生错误的代码
except 异常类型:
    如果捕获到该异常类型, 执行的代码
"""
try:
    print(num)  # NameError: name 'num' is not defined
except NameError:
    print('有错误')

# 结果:
# 有错误
```

### 2.2. 捕获多个指定异常类型

```py
try:
    print(1 / 0)  # ZeroDivisionError: division by zero
except (NameError, ZeroDivisionError):
    print('有错误')

# 结果:
# 有错误
```

### 2.3. 捕获异常描述信息

```py
try:
    print(num)
except (NameError, ZeroDivisionError) as result:
    print(result)

# 结果:
# name 'num' is not defined
```

### 2.4. 捕获所有异常

Exception 是所有程序异常类的父类

```py
try:
    print(num)
except Exception as result:
    print(result)

# 结果:
# name 'num' is not defined
```

## 3. else 子句

else 表示没有异常时会执行的代码

```py
try:
    print(1)
except Exception as result:
    print(result)
else:
    print('没有异常时执行的代码')

# 结果:
# 1
# 没有异常时执行的代码
```

## 4. finally 子句

finally 表示无论是否有异常都会执行的代码，例如关闭文件

```py
try:
    f = open('test.txt', 'r')
except Exception as result:
    f = open('test.txt', 'w')
else:
    print('打开文件时没有发生异常')
finally:
    f.close()
```

## 5. 异常的传递

```py
import time

try:
    f = open('test.txt')
    try:
        while True:
            content = f.readline()
            if len(content) == 0:
                break
            time.sleep(2)
            print(content)
    except:
        # 读取过程中如果检测到用户意外终止程序, 则捕获异常
        # 例如按下 Ctrl + C 强制中断程序
        print('程序被意外终止')
    finally:
        f.close()
except:
    print('文件不存在')

# 结果:
# ^C程序被意外终止
```

## 6. 自定义异常

```py
"""
raise 异常对象  # 抛出异常
"""
# 自定义异常类, 继承于 Exception
class ShortInputError(Exception):
    def __init__(self, length, min_length):
        self.length = length
        self.min_length = min_length

    # 设置抛出异常的描述信息
    def __str__(self):
        return f'你输入的密码长度为 {self.length}, 密码长度不能少于 {self.min_length} 个字符'


def main():
    try:
        content = input('请输入密码: ')
        if len(content) < 3:
            raise ShortInputError(len(content), 3)
    except Exception as result:
        print(result)
    else:
        print('密码输入成功')


if __name__ == '__main__':
    main()

# 结果:
# 请输入密码: 12
# 你输入的密码长度为 2, 密码长度不能少于 3 个字符

# 结果:
# 请输入密码: 123
# 密码输入成功
```
